### PR TITLE
implement internal strlcpy to replace the strncpy (https://github.com/OpenAMP/open-amp/pull/620)

### PR DESCRIPTION
**Pull request by tejlmand**
Cherry-pick of Open-amp upstream PR https://github.com/OpenAMP/open-amp/pull/620.

Upstream PR has been adjusted to match the filtering and path adjustment (open-amp sub-folder) in the Zephyr fork.

### CODE REVIEW

**Comment by carlescufi** [comment]
@arnopo @carlocaione could you please take a look?

**Comment by arnopo** [comment]
Hi, 
The process generally applied for this repository is to realign the main branch on the OpenAMP library:
- Realign on a specific commit to fix an issue.
- Realign on the OpenAMP release (the next one is planned for the end of this month).

Is this PR blocking something, or can we wait for the next OpenAMP release?

**Comment by carlescufi** [comment]
> Hi, The process generally applied for this repository is to realign the main branch on the OpenAMP library:
> 
> * Realign on a specific commit to fix an issue.
> * Realign on the OpenAMP release (the next one is planned for the end of this month).
> 
> Is this PR blocking something, or can we wait for the next OpenAMP release?

@arnopo 
This is causing build failures in some of our applications, notably:
```
../../../../../../../modules/lib/open-amp/open-amp/lib/remoteproc/remoteproc.c: In function 'remoteproc_init_mem':
../../../../../../../modules/lib/open-amp/open-amp/lib/remoteproc/remoteproc.c:303:17: error: 'strncpy' specified bound 32 equals destination size [-Werror=stringop-truncation]
  303 |                 strncpy(mem->name, name, sizeof(mem->name));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
so we would require a fix if possible.

**Comment by carlescufi** [comment]
@arnopo could you perhaps merge https://github.com/OpenAMP/open-amp/pull/620 so we can then update up to that revision?

**Comment by arnopo** [comment]
> @arnopo could you perhaps merge [OpenAMP/open-amp#620](https://github.com/OpenAMP/open-amp/pull/620) so we can then update up to that revision?

[OpenAMP/open-amp#620](https://github.com/OpenAMP/open-amp/pull/620 is not ready to be merge.
As it is a blocker, let's merge this one and then we will rebase/overwrite on the next OpenAMP release.

**Review by arnopo — APPROVED** [review]

**Comment by carlescufi** [comment]
@tejlmand SHA: b735edbc739ad59156eb55bb8ce2583d74537719

**Comment by tomi-font** [comment]
Hey, not sure if that matters, but the upstream PR's author made an update to define the function as weak (`metal_weak`, more precisely).

**Pull request merged**
