### PR TITLE
lib: update open-amp lib to release v2020.10.0

### PR DESCRIPTION
**Pull request by galak**
Origin:
        https://github.com/OpenAMP/open-amp

Commit:
        4d20dcdca51332995aae09e050cd2e772543e187

Status:
        merge open-amp new version after removing the apps dir.

Release Description:
        https://github.com/OpenAMP/open-amp/releases/tag/v2020.10.0

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@arnopo FYI

**Comment by galak** [comment]
Zephyr side PR https://github.com/zephyrproject-rtos/zephyr/pull/29490

**Comment by galak** [comment]
I think this should include what PR #8 is doing.

**Review by carlescufi — APPROVED** [review]

**Comment by arnopo** [comment]
> I think this should include what PR #8 is doing.

I confirm

**Review by arnopo — APPROVED** [review]

**Pull request merged**
