### PR TITLE
V2020.01.0

### PR DESCRIPTION
**Pull request by arnopo**
update to ope-amp release V2020.01.0

### CODE REVIEW

**Comment by arnopo** [comment]
Dependency with https://github.com/zephyrproject-rtos/libmetal/pull/1

**Comment by arnopo** [comment]
@ioannisg , @edmooring @karl-zh 
Could you please review and check that does not introduce regression on your platform
Thanks!

**Comment by galak** [comment]
Do we need compiler.h?  I'm not seeing that in the open-amp repo.

**Comment by galak** [comment]
> Do we need compiler.h? I'm not seeing that in the open-amp repo.

nevermind, was looking at the wrong version

**Comment by galak** [comment]
Testing via https://github.com/zephyrproject-rtos/zephyr/pull/23810

**Review by galak — APPROVED** [review]

**Pull request merged**
