### PR TITLE
lib: update open-amp lib to release v2024.05.0

### PR DESCRIPTION
**Pull request by carlocaione**
Origin:
	https://github.com/OpenAMP/open-amp

Commit:
	e9eef7ce57c361eec7b4006c537d26ced0e02aec

Status:
	merge open-amp new version after removing the apps dir.

Release Description:
	https://github.com/OpenAMP/open-amp/releases/tag/v2024.05.0

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by carlocaione** [comment]
@nashif this was not to be merged as is. We were waiting for https://github.com/OpenAMP/open-amp/pull/596 to be in before reworking this.

**Comment by carlocaione** [comment]
@arnopo @nashif how do we want to fix this. I'm tempted to just force-push on top given that currently no-one is using the `master` branch.

**Comment by arnopo** [comment]
> how do we want to fix this. I'm tempted to just force-push on top given that currently no-one is using the `master` branch.

That seems ok to me

**Comment by carlocaione** [comment]
Ok, the plan here is to force push to reset the current `HEAD` to https://github.com/zephyrproject-rtos/open-amp/commit/da78aea63159771956fe0c9263f2e6985b66e9d5 and after that I'll push a new PR with the bump.

**Pull request merged**
