### PR TITLE
Open-AMP update to SHA 5fce292fd447

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Open-AMP update to SHA 5fce292fd447c2396731efeb7852ab7d84454aa1 - https://github.com/OpenAMP/open-amp/commits/main

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
@carlocaione @arnopo please review
Thanks

**Comment by iuliana-prodan** [comment]
In this PR I've taken also this commit : https://github.com/OpenAMP/open-amp/commit/e63d07d10577b06c5b3fc8e1c20ede74779d3132 and I get the following warnings:
```
[5/168] Generating include/generated/version.h
-- Zephyr version: 3.4.99 (/home/nxa06898/data/zephyrproject/zephyr), build: zephyr-v3.4.0-4679-g8f0d319d8f2b
[66/168] Building C object zephyr/CMakeFiles/zephyr.dir/lib/open-amp/resource_table.c.obj
In file included from /home/nxa06898/data/zephyrproject/zephyr/lib/open-amp/resource_table.c:30:
/home/nxa06898/data/zephyrproject/zephyr/lib/open-amp/./resource_table.h:29: warning: "VRING_ALIGNMENT" redefined
   29 | #define VRING_ALIGNMENT         16  /* fixed to match with Linux constraint */
      | 
In file included from /home/nxa06898/data/zephyrproject/zephyr/lib/open-amp/./resource_table.h:11:
/home/nxa06898/data/zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/virtio.h:139: note: this is the location of the previous definition
  139 | #define VRING_ALIGNMENT           4096
      | 
[158/168] Building C object CMakeFiles/app.dir/src/main_remote.c.obj
In file included from /home/nxa06898/data/zephyrproject/zephyr/samples/subsys/ipc/openamp_rsc_table/src/main_remote.c:18:
/home/nxa06898/data/zephyrproject/zephyr/lib/open-amp/./resource_table.h:29: warning: "VRING_ALIGNMENT" redefined
   29 | #define VRING_ALIGNMENT         16  /* fixed to match with Linux constraint */
      | 
In file included from /home/nxa06898/data/zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/rpmsg_virtio.h:19,
                 from /home/nxa06898/data/zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/open_amp.h:12,
                 from /home/nxa06898/data/zephyrproject/zephyr/samples/subsys/ipc/openamp_rsc_table/src/main_remote.c:16:
/home/nxa06898/data/zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/virtio.h:139: note: this is the location of the previous definition
  139 | #define VRING_ALIGNMENT           4096
      | 
```

when compiling openamp_rsc_table sample for nxp_adsp_imx8m: `west build -p always -b nxp_adsp_imx8m samples/subsys/ipc/openamp_rsc_table`

Not quite sure how to fix this.
Why was `VRING_ALIGNMENT` added [here](https://github.com/OpenAMP/open-amp/blob/main/lib/include/openamp/virtio.h#L139) in this https://github.com/OpenAMP/open-amp/commit/e63d07d10577b06c5b3fc8e1c20ede74779d3132 ?

**Comment by carlocaione** [comment]
Probably @arnopo must take a look here but it looks a name clash to me. Maybe we can rename the zephyr define?

**Comment by arnopo** [comment]
> Probably @arnopo must take a look here but it looks a name clash to me. Maybe we can rename the zephyr define?

The issue is in open-amp lib. the VRING_ALIGNMENT is a system definition that should be common to the main and the coprocessor.
Could you send a patch on open-amp that removes VRING_ALIGNMENT and VRING_DECLARE definition?
They are not used yet and generate a regression, so should be removed for the coming release.

**Comment by iuliana-prodan** [comment]
> > Probably @arnopo must take a look here but it looks a name clash to me. Maybe we can rename the zephyr define?
> 
> The issue is in open-amp lib. the VRING_ALIGNMENT is a system definition that should be common to the main and the coprocessor. Could you send a patch on open-amp that removes VRING_ALIGNMENT and VRING_DECLARE definition? They are not used yet and generate a regression, so should be removed for the coming release.

I see that a PR was created: https://github.com/OpenAMP/open-amp/pull/505

I'll wait for this PR, from open-amp repo, to be merge and then I'll update mine.
Hope it's ok with you @arnopo @carlocaione

**Comment by arnopo** [comment]
> > > Probably @arnopo must take a look here but it looks a name clash to me. Maybe we can rename the zephyr define?
> > 
> > 
> > The issue is in open-amp lib. the VRING_ALIGNMENT is a system definition that should be common to the main and the coprocessor. Could you send a patch on open-amp that removes VRING_ALIGNMENT and VRING_DECLARE definition? They are not used yet and generate a regression, so should be removed for the coming release.
> 
> I see that a PR was created: [OpenAMP/open-amp#505](https://github.com/OpenAMP/open-amp/pull/505)
> 
> I'll wait for this PR, from open-amp repo, to be merge and then I'll update mine. Hope it's ok with you @arnopo @carlocaione

@iuliana-prodan 
Please, could you have a short test to confirm that https://github.com/OpenAMP/open-amp/pull/505 fix the issue?
Then for your information the open-amp Libraries should be release at the end of this month. I don't know if you want/can wait the release to align the open-amp Zephyr repository.

**Comment by iuliana-prodan** [comment]
> > > > Probably @arnopo must take a look here but it looks a name clash to me. Maybe we can rename the zephyr define?
> > > 
> > > 
> > > The issue is in open-amp lib. the VRING_ALIGNMENT is a system definition that should be common to the main and the coprocessor. Could you send a patch on open-amp that removes VRING_ALIGNMENT and VRING_DECLARE definition? They are not used yet and generate a regression, so should be removed for the coming release.
> > 
> > 
> > I see that a PR was created: [OpenAMP/open-amp#505](https://github.com/OpenAMP/open-amp/pull/505)
> > I'll wait for this PR, from open-amp repo, to be merge and then I'll update mine. Hope it's ok with you @arnopo @carlocaione
> 
> @iuliana-prodan Please, could you have a short test to confirm that [OpenAMP/open-amp#505](https://github.com/OpenAMP/open-amp/pull/505) fix the issue? 

Yes, I've tested it and everything works perfectly.

>Then for your information the open-amp Libraries should be release at the end of this month. I don't know if you want/can wait the release to align the open-amp Zephyr repository.

@carlocaione what do you think about this?
Should we wait for the open-amp release?

**Comment by carlocaione** [comment]
> @carlocaione what do you think about this? Should we wait for the open-amp release?

At least we should wait for that fix to be merged, then we can update this commit with the new SHA.

**Comment by iuliana-prodan** [comment]
> > @carlocaione what do you think about this? Should we wait for the open-amp release?
> 
> At least we should wait for that fix to be merged, then we can update this commit with the new SHA.

Updated open-amp to 5fce292fd447c2396731efeb7852ab7d84454aa1 from https://github.com/OpenAMP/open-amp/commits/main

**Review by carlocaione — APPROVED** [review]

**Review by arnopo — APPROVED** [review]

**Comment by arnopo** [comment]
@carlocaione 
I let you merge it,

**Comment by carlocaione** [comment]
@iuliana-prodan after the freeze is over please push a Zephyr commit to update the manifest SHA

**Comment by iuliana-prodan** [comment]
> @iuliana-prodan after the freeze is over please push a Zephyr commit to update the manifest SHA

https://github.com/zephyrproject-rtos/zephyr/pull/64364

**Pull request merged**
